# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Eunjin Choi
tagline:          
description:      'jech@kaist.ac.kr'
url:              http://jech2.github.io/
baseurl:          ''

author:
  name:           'Eunjin Choi'
  url:            https://jech-jose.tistory.com/
  soundcloud :    https://soundcloud.com/jech_2
  email :         jech@kaist.ac.kr


paginate:         5

# Custom vars
version:          1.1.0

github:
  repo:           https://github.com/JECH2

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-redirect-from